name: create template issue
on:
  - workflow_dispatch
permissions:
  contents: read
  issues: write 
jobs:
  create-template-issue:
    strategy:
      matrix:
        filename: ["1", "2", "3", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get parent hash
        run: echo "PARENT_COUNT=$(git rev-parse HEAD^@ | wc -l)" >> $GITHUB_ENV
      - name: Create template issue
        if: env.PARENT_COUNT == 0
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/issues/${{ matrix.filename }}.md
